import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {importTS} from './load-module.mjs';
const {CodeEq}=await importTS(new URL('../app/code-eq.ts',import.meta.url));
const {AudioFrameDeriver}=await importTS(new URL('../app/audio-analysis.ts',import.meta.url));
const {Framebuffer}=await importTS(new URL('../app/framebuffer.ts',import.meta.url));
const {AudioFrameStore,encodeAudio}=await importTS(new URL('../app/audio-frame.ts',import.meta.url));
const {Visualizer,vizDefaults}=await importTS(new URL('../app/visualizer.ts',import.meta.url));
const fixture=JSON.parse(readFileSync(new URL('./fixtures/code-eq-reference.json',import.meta.url)));
function sample(n){const level=Float64Array.from({length:32},(_,c)=>n<60?0:n>=260?1:((n*7+c*11)%101)/100);return {level,peak:Float64Array.from(level,x=>n>=60?Math.min(1,x+.2):0),bass:level.slice(0,8).reduce((a,b)=>a+b,0)/8,mid:level.slice(8,24).reduce((a,b)=>a+b,0)/16,treble:level.slice(24).reduce((a,b)=>a+b,0)/8,beat:[80,110,170,230].includes(n),strength:.7};}
function hash(frame){const bytes=new Uint8Array(8192*3);frame.pixels.forEach((p,i)=>{bytes[i*3]=p>>16;bytes[i*3+1]=p>>8;bytes[i*3+2]=p;});return createHash('sha256').update(bytes).digest('hex');}
test('Code EQ matches 300 upstream Python reference frames exactly',()=>{const fx=new CodeEq(),frame=new Framebuffer();for(let n=0;n<300;n++){fx.update(sample(n));frame.clear('#000000');fx.draw(frame,1/60);assert.equal(hash(frame),fixture.sha256[n],`frame ${n}`);}});
test('beat glitch can be disabled without disabling bars or background rain',()=>{const a=new CodeEq(),b=new CodeEq(),fa=new Framebuffer(),fb=new Framebuffer();for(let n=0;n<120;n++){const f=sample(n);a.update(f,false);b.update({...f,beat:false});fa.clear('#000000');fb.clear('#000000');a.draw(fa,1/60);b.draw(fb,1/60);assert.deepEqual(fa.pixels,fb.pixels);}assert.ok(fa.pixels.some(v=>v!==0));});
test('packet analysis holds peaks, detects bass rise once and suppresses silence beats',()=>{const d=new AudioFrameDeriver(),zero=new Uint8Array(32),loud=new Uint8Array(32).fill(255);for(let i=0;i<25;i++)assert.equal(d.feed(zero,.04).beat,false);const rise=d.feed(loud,.04);assert.equal(rise.beat,true);assert.ok(rise.level[0]>.95);assert.equal(d.feed(loud,.04).beat,false);const held=d.feed(zero,.04);assert.ok(held.peak[0]>held.level[0]);let last;for(let i=0;i<100;i++){last=d.feed(zero,.04);assert.equal(last.beat,false);}assert.ok(last.peak[0]<.001);assert.throws(()=>d.feed(new Uint8Array(1),.04));assert.ok(d.feed(zero,NaN).level.every(Number.isFinite));});
test('frame history is bounded, ordered, owned and cleared with the input',()=>{const s=new AudioFrameStore(),p=encodeAudio(new Uint8Array(32),null);for(let i=0;i<200;i++)s.ingest(p,i*40);assert.equal(s.framesAfter(0).length,128);assert.equal(s.framesAfter(199).length,1);assert.equal(s.framesAfter(200).length,0);s.clear();assert.equal(s.framesAfter(0).length,0);});
test('slow display consumes all packets once, including a beat before the latest packet',()=>{const s=new AudioFrameStore(),v=new Visualizer(),o={...vizDefaults,effect:15,showClock:false},clock={zone:'UTC',hour24:true};const zero=new Uint8Array(32),loud=new Uint8Array(32).fill(255);for(let i=0;i<25;i++)s.ingest(encodeAudio(zero,null),i*40);v.render(s,960,o,clock,null);s.ingest(encodeAudio(loud,null),1000);s.ingest(encodeAudio(loud,null),1040);v.render(s,1040,o,clock,null);assert.ok(v.codeEq.glitch>0);const glitch=v.codeEq.glitch;v.render(s,1045,o,clock,null);assert.ok(v.codeEq.glitch<glitch);assert.equal(v.audioSerial,27);});
test('packet analysis agrees with 160 native C++ frames',()=>{const expected=JSON.parse(readFileSync(new URL('./fixtures/audio-analysis-reference.json',import.meta.url))),d=new AudioFrameDeriver();for(let n=0;n<expected.length;n++){const bands=Uint8Array.from({length:32},(_,c)=>n<25||n>=100?0:n%20<3?255:(n*7+c*11)%180),actual=d.feed(bands,.04),ref=expected[n];assert.equal(actual.beat,!!ref.beat,`beat ${n}`);for(const key of ['strength','bass','mid','treble'])assert.ok(Math.abs(actual[key]-ref[key])<1e-5,`${key} ${n}`);for(const key of ['level','peak'])actual[key].forEach((v,i)=>assert.ok(Math.abs(v-ref[key][i])<1e-5,`${key} ${n}:${i}`));}});
