'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Maximize,Play,Pause,RotateCcw,ChevronRight,Sun,Grid2X2} from 'lucide-react';
import {renderClock,resetTetris,styles,type Options} from './renderer';
const defaults:Options={style:'Tetris',brightness:85,hour24:true,date:true,blink:true,glow:true,zone:'local',color:'#64e6ac',motion:true};
export default function Home(){
 const [o,setO]=useState(defaults),[ready,setReady]=useState(false),[cycle,setCycle]=useState(false),[replay,setReplay]=useState(0),[now,setNow]=useState(new Date(0)),[error,setError]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null), panel=useRef<HTMLDivElement>(null);
 const animationTime=useRef(0),previousReplay=useRef(0);
 useEffect(()=>{animationTime.current=0;if(canvas.current)resetTetris(canvas.current,replay!==previousReplay.current);previousReplay.current=replay},[o.style,replay]);
 const update=(patch:Partial<Options>)=>setO(v=>({...v,...patch}));
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('pixel-clock')||'null');if(saved&&styles.includes(saved.style)){new Intl.DateTimeFormat('en',{timeZone:saved.zone==='local'?undefined:saved.zone});setO({...defaults,...saved});}}catch{}setReady(true);setNow(new Date());const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('pixel-clock',JSON.stringify(o))}catch{}},[o,ready]);
 useEffect(()=>{if(!cycle)return;const t=setInterval(()=>setO(v=>({...v,style:styles[(styles.indexOf(v.style)+1)%styles.length]})),20000);return()=>clearInterval(t)},[cycle]);
 useEffect(()=>{if(!canvas.current)return;let frame=0;let previous=performance.now();const draw=(t:number)=>{const elapsed=t-previous;previous=t;if(o.motion)animationTime.current+=elapsed/1000;renderClock(canvas.current!,o,animationTime.current,new Date());frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[o,replay]);
 useEffect(()=>{
 const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!ctx?.registerTool)return;
 const lifecycle=new AbortController();
 try{Promise.resolve(ctx.registerTool({name:'set_clock_style',description:'Select an arcade clock style and stop automatic rotation.',inputSchema:{type:'object',properties:{style:{type:'string',enum:styles}},required:['style'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const style=(input as {style?:string})?.style;if(!style||!styles.includes(style))throw new Error('Choose a supported clock style');flushSync(()=>{setCycle(false);setO(v=>({...v,style}))});return {style,cycling:false}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 return()=>lifecycle.abort();
 },[]);
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await panel.current?.requestFullscreen()}catch{setError('Fullscreen is unavailable in this browser. Open the clock in a separate browser window.')}};
 return <main><header><a className="brand" href="/" aria-label="Pixel Clock home"><span className="brandmark"><Grid2X2 size={22}/></span>PIXEL<span className="brand-light">CLOCK</span></a><span className="edition">THE ARCADE COLLECTION <span> / </span> WEB EDITION</span><span className="live"><i/> LIVE</span></header>
 <section className="workspace"><div className="intro"><div><p className="eyebrow">A LITTLE ARCADE. ALL THE TIME.</p><h1>Time, in pixels.</h1></div><button className="quiet" onClick={full}><Maximize size={16}/> Fullscreen</button></div>
 <div className="display-section" ref={panel}><div className="device"><div className="device-top"><span>ANIMATED PIXEL CLOCK</span><span>128 × 64 RGB</span></div><div className={'screen '+(o.glow?'bloom':'')} style={{filter:`brightness(${o.brightness/100})`}}><canvas ref={canvas} width={1024} height={512} aria-label={`${o.style} clock, ${ready?now.toLocaleTimeString('en-AU',{timeZone:o.zone==='local'?undefined:o.zone,hour12:!o.hour24}):'loading'}`}/></div><div className="device-bottom"><span><i/> {o.style.toUpperCase()}</span><span>● ● ●</span></div></div><button className="exit-full" onClick={full}>Exit fullscreen</button></div>
 <div className="playback"><div><span className="status-dot"/>{o.style}<span className="muted"> / {o.motion?'Animation running':'Motion paused'}</span></div><div className="playback-actions"><button title={o.motion?'Pause animation':'Resume animation'} aria-label={o.motion?'Pause animation':'Resume animation'} onClick={()=>update({motion:!o.motion})}>{o.motion?<Pause size={17}/>:<Play size={17}/>}</button><button title="Replay digit animation" aria-label="Replay digit animation" onClick={()=>{update({motion:true});setReplay(v=>v+1)}}><RotateCcw size={17}/></button><button title="Next style" aria-label="Next style" onClick={()=>update({style:styles[(styles.indexOf(o.style)+1)%styles.length]})}><ChevronRight size={20}/></button></div></div>
 <div className="lower"><section className="collection"><div className="section-heading"><h2>Choose your clock</h2><label className="toggle">Cycle every 20s <Switch checked={cycle} onCheckedChange={setCycle} aria-label="Cycle styles every 20 seconds"/></label></div><div className="styles">{styles.map((s,i)=><button key={s} className={'style-card '+(s===o.style?'selected':'')} onClick={()=>{setCycle(false);update({style:s})}} aria-pressed={s===o.style}><span className="style-glyph" style={{color:['#63e4aa','#ffb25b','#ba9cff','#f9d966','#59dcff'][i%5]}}>{['▟','▥','◉','⌁','▦','✦','⌐','↟','▧','╬','▣','◷','▤'][i]}</span><span>{s}</span><span className="selected-dot"/></button>)}</div></section>
 <aside className="settings"><h2>Display settings</h2><div className="brightness"><label id="brightness"><Sun size={15}/> Brightness</label><output>{o.brightness}%</output></div><Slider aria-labelledby="brightness" min={10} max={100} value={[o.brightness]} onValueChange={v=>update({brightness:Array.isArray(v)?v[0]:v})}/><div className="setting-row"><label htmlFor="hour24">24-hour time</label><Switch id="hour24" checked={o.hour24} onCheckedChange={v=>update({hour24:v})}/></div><div className="setting-row"><label htmlFor="date">Show date</label><Switch id="date" checked={o.date} onCheckedChange={v=>update({date:v})}/></div><div className="setting-row"><label htmlFor="glow">LED glow</label><Switch id="glow" checked={o.glow} onCheckedChange={v=>update({glow:v})}/></div><div className="setting-row"><label htmlFor="blink">Blink colon</label><Switch id="blink" checked={o.blink} onCheckedChange={v=>update({blink:v})}/></div><div className="setting-row"><label htmlFor="color">Digit color</label><input id="color" type="color" value={o.color} onChange={e=>update({color:e.target.value})}/></div><label className="zone-label" id="zone-label">Timezone</label><Select value={o.zone} onValueChange={v=>v&&update({zone:v})}><SelectTrigger aria-labelledby="zone-label" className="zone-select"><SelectValue/></SelectTrigger><SelectContent>{['local',...Intl.supportedValuesOf('timeZone')].map(z=><SelectItem key={z} value={z}>{z==='local'?'Device timezone':z.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select></aside></div>
 {error&&<p role="alert">{error}</p>}<footer><span>Inspired by AnimatedPixelClock <span className="muted">· 13 browser clock styles</span></span><span>Your time. Your timezone. <span className="footer-pixel">▪</span></span></footer></section></main>
}
